---
- name: Deploy OpenLDAP Server with users, ssh keys, autoFS configurations
  hosts: all
  remote_user: root
  gather_facts: yes
  tasks:
    - import_role:
        name: common
    - import_role:
        name: openldap
      when:  openldap_server_ip is defined and openldap_server_ip != None
    - import_role:
        name: ceph-fs
      when:
        - shared_storage
        - storage_backend == "cephfs"
    - import_role:
        name: telegraf
      when: "'telegraf' in group_names"
