---
- name: Copy Samba configuration
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
  notify: smbldap populate

- name: Copy smbldap.conf
  template:
    src: smbldap.conf.j2
    dest: /etc/smbldap-tools/smbldap.conf
  notify: smbldap populate

- name: Copy smbldap_bind.conf
  template:
    src: smbldap_bind.conf.j2
    dest: /etc/smbldap-tools/smbldap_bind.conf
  notify: smbldap populate

- meta: flush_handlers

- name: Populate smbldap database
  shell: |
    smbldap-populate -g 10000 -u 10000 -r 10000 <<EOF
    {{ openldap_server_rootpw }}
    {{ openldap_server_rootpw }}
    EOF
  args:
    executable: /bin/bash
  when: smbldap_populate is defined and smbldap_populate

- name: "Add users to Samba"
  shell: |
    smbpasswd -s -a {{ item.key }} <<EOF
    {{ item.value.password }}
    {{ item.value.password }}
    EOF
  args:
    executable: /bin/bash
  loop: "{{ ssh_users | dict2items }}"
  when: smbldap_populate is defined and smbldap_populate

- name: Inform Samba about RootDN password
  shell: "smbpasswd -w {{ openldap_server_rootpw }}"
  when: smbldap_populate is defined and smbldap_populate

- name: restart samba services
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  loop:
    - nmbd
    - smbd
  when: smbldap_populate is defined and smbldap_populate
