---

- name: Admin OU
  ldap_entry:
    bind_dn: "{{ openldap_server_bind_dn }}"
    bind_pw: "{{ openldap_server_rootpw }}"
    dn: "{{ admin_ou }}"
    objectClass:
      - top
      - organizationalUnit
    attributes:
      ou: admin
    state: present
  notify: restart nscd

- name: Automount OU
  ldap_entry:
    bind_dn: "{{ openldap_server_bind_dn }}"
    bind_pw: "{{ openldap_server_rootpw }}"
    dn: "{{ automount_ou }}"
    objectClass:
      - top
      - organizationalUnit
    attributes:
      ou: automount
    state: present
  notify: restart nscd

- name: auto.master OU
  ldap_entry:
    bind_dn: "{{ openldap_server_bind_dn }}"
    bind_pw: "{{ openldap_server_rootpw }}"
    dn: "{{ auto_master_ou }}"
    objectClass:
      - top
      - automountMap
    attributes:
      ou: auto.master
    state: present
  notify: restart nscd

- name: CephFS data automount CN
  ldap_entry:
    bind_dn: "{{ openldap_server_bind_dn }}"
    bind_pw: "{{ openldap_server_rootpw }}"
    dn: "cn=/-,{{ auto_master_ou }}"
    objectClass:
      - top
      - automount
    attributes:
      cn: "/-"
      automountInformation: "ldap:ou=auto.data,ou=automount,ou=admin,{{ openldap_server_dc }} --ghost"
    state: present
  notify: restart nscd
  when: storage_backend == "cephfs"

- name: NFS data automount CN
  ldap_entry:
    bind_dn: "{{ openldap_server_bind_dn }}"
    bind_pw: "{{ openldap_server_rootpw }}"
    dn: "cn={{ data_mount_root }},{{ auto_master_ou }}"
    objectClass:
      - top
      - automount
    attributes:
      cn: "{{ data_mount_root }}"
      automountInformation: "ldap:ou=auto.data,ou=automount,ou=admin,{{ openldap_server_dc }} --ghost"
    state: present
  notify: restart nscd
  when: storage_backend == "nfs"

- name: auto.data OU
  ldap_entry:
    bind_dn: "{{ openldap_server_bind_dn }}"
    bind_pw: "{{ openldap_server_rootpw }}"
    dn: "{{ auto_data_ou }}"
    objectClass:
      - top
      - automountMap
    attributes:
      ou: auto.data
    state: present
  notify: restart nscd

- name: CephFS Data Directory CNs
  ldap_entry:
    bind_dn: "{{ openldap_server_bind_dn }}"
    bind_pw: "{{ openldap_server_rootpw }}"
    dn: "cn=/data,{{ auto_data_ou }}"
    objectClass:
      - top
      - automount
    attributes:
      cn: "/data"
      automountInformation: "-fstype=ceph {{ groups['mdss'] | join(':6789,') }}:6789:/"
    state: present
  notify: restart nscd
  when: storage_backend == "cephfs"

- name: NFS Data Directory CNs
  ldap_entry:
    bind_dn: "{{ openldap_server_bind_dn }}"
    bind_pw: "{{ openldap_server_rootpw }}"
    dn: "cn={{ item.key }},{{ auto_data_ou }}"
    objectClass:
      - top
      - automount
    attributes:
      cn: "{{ item.key }}"
      automountInformation: "-fstype=nfs,{{ item.value.mount_opts }} {{ nfs_server_ip }}:{{ item.value.nfs_export }}"
    state: present
  notify: restart nscd
  with_dict: "{{ nfs_exports }}"
  when: storage_backend == "nfs"

- name: Home automount CN
  ldap_entry:
    bind_dn: "{{ openldap_server_bind_dn }}"
    bind_pw: "{{ openldap_server_rootpw }}"
    dn: "cn=/home,{{ auto_master_ou }}"
    objectClass:
      - top
      - automount
    attributes:
      cn: /home
      automountInformation: "ldap:ou=auto.home,ou=automount,ou=admin,{{ openldap_server_dc }} --timeout=60 --ghost"
    state: present
  notify: restart nscd

- name: auto.home OU
  ldap_entry:
    bind_dn: "{{ openldap_server_bind_dn }}"
    bind_pw: "{{ openldap_server_rootpw }}"
    dn: "{{ auto_home_ou }}"
    objectClass:
      - top
      - automountMap
    attributes:
      ou: auto.home
    state: present
  notify: restart nscd

- name: User Directory CNs
  ldap_entry:
    bind_dn: "{{ openldap_server_bind_dn }}"
    bind_pw: "{{ openldap_server_rootpw }}"
    dn: "cn={{ item.key }},{{ auto_home_ou }}"
    objectClass:
      - top
      - automount
    attributes:
      cn: "{{ item.key }}"
      automountInformation: "-fstype=ceph {{ groups['mdss'] | join(':6789,') }}:6789:/{{ ldap_user_home_directory }}/{{ item.key }}"
    state: present
  notify: restart nscd
  with_dict: "{{ ssh_users }}"
  when: storage_backend == "cephfs"

- name: create user home directories
  file:
    state: directory
    path: "{{ data_mount_root }}/{{ ldap_user_home_directory }}/{{ item.key }}"
    owner: "{{ item.value.uid }}"
    group: "{{ item.value.gid }}"
    mode: 0755
  with_dict: "{{ ssh_users }}"
  when: storage_backend == "nfs"

- name: User Directory CNs
  ldap_entry:
    bind_dn: "{{ openldap_server_bind_dn }}"
    bind_pw: "{{ openldap_server_rootpw }}"
    dn: "cn={{ item.key }},{{ auto_home_ou }}"
    objectClass:
      - top
      - automount
    attributes:
      cn: "{{ item.key }}"
      automountInformation: "-fstype=nfs,{{ nfs_exports.homedirs.mount_opts }} {{ nfs_server_ip }}:{{ nfs_exports.homedirs.nfs_export }}/{{ item.key }}"
    state: present
  notify: restart nscd
  with_dict: "{{ ssh_users }}"
  when: storage_backend == "nfs"

- meta: flush_handlers
