---
- name: Install the openldap and required Packages for RedHat
  ansible.builtin.yum:
    name: "{{ openldap_server_pkgs }}"
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install the openldap and required Packages for Ubuntu
  ansible.builtin.apt:
    name: "{{ openldap_server_pkgs }}"
    state: present
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: Install ansible python dependencies for openldap configuration
  ansible.builtin.pip:
    name: "{{ openldap_python_pkgs }}"
    state: present
