---
- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Add /etc/hosts entry for ldap server
  lineinfile:
    dest: /etc/hosts
    state: present
    line: "{{openldap_server_ip}} {{openldap_server_domain_name}}"
    
- name: Install the openldap and required Packages for RedHat
  yum:
    name: "{{ openldap_server_pkgs }}"
    state: present
  when: ansible_os_family == 'RedHat'


- name: Install the openldap and required Packages for Ubuntu
  apt:
    name: "{{ openldap_server_pkgs }}"
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: copy openssh-lpk schema file
  copy:
    src: openssh-lpk
    dest: /etc/ldap/schema/openssh-lpk.schema
    mode: 0644
  notify:
   - restart slapd

- name: Delete the configuration directory
  file: path={{ openldap_server_app_path }}/slapd.d state=absent

- name: Generate the root password for ldap
  shell: slappasswd -s {{ openldap_server_rootpw }} 
  register: root_password
  no_log: True

- name: Copy the slapd.conf configuration file for Redhat
  template: 
    src: slapd.conf.j2
    dest: "{{ openldap_server_app_path }}/slapd.conf"
  when: ansible_os_family == "RedHat"
  notify: 
   - restart slapd

- name: Copy the slapd.conf configuration file
  template: src=slapd.conf_ubuntu.j2 dest={{ openldap_server_app_path }}/slapd.conf
  when: ansible_os_family == "Debian"
  notify: 
   - restart slapd

- name: Copy the ldap.conf configuration file
  template: src=ldap.conf.j2 dest={{ openldap_server_app_path }}/ldap.conf

#- name: PIP python-ldap
#  pip:
#    executable: /usr/bin/pip3
#    name: python3-ldap3
#    state: present

#- name: PIP python expect
#  pip:
#    executable: /usr/bin/pip3
#    name: pexpect
#    state: present

