---
- name: Wait for locks
  ansible.builtin.include_tasks:
    file: wait_for_locks.yml

- name: Install the openldap and required Packages for RedHat
  ansible.builtin.dnf:
    name: "{{ openldap_server_pkgs }}"
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install the openldap and required Packages for Ubuntu
  ansible.builtin.apt:
    name: "{{ openldap_server_pkgs }}"
    state: present
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: Install ansible python dependencies for openldap configuration
  ansible.builtin.pip:
    name: "{{ openldap_python_pkgs }}"
    state: present
