---
- name: Wait for locks
  ansible.builtin.include_tasks:
    file: wait_for_locks.yml

- name: Install SSSD + LDAP client packages
  ansible.builtin.package:
    name: "{{ openldap_client_pkgs }}"
    state: present
    update_cache: true
  register: openldap_client_pkg_install
  until: openldap_client_pkg_install is not failed

- name: Remove nscd and nslcd if present
  ansible.builtin.package:
    name:
      - nscd
      - nslcd
    state: absent

# - name: Set sudo alternative to classic sudo.ws (Ubuntu 26.04)
#   changed_when: true
#   when:
#     - ansible_distribution == 'Ubuntu'
#     - ansible_distribution_major_version == '26'
#   notify:
#     - restart_login_services
#   ansible.builtin.command: update-alternatives --set sudo /usr/bin/sudo.ws

- name: Ensure paths for openldap, sssd and authselect configs exist
  ansible.builtin.file:
    state: directory
    dest: "{{ item }}"
    mode: "0644"
  loop:
    - "{{ openldap_server_app_path }}"
    - "/etc/sssd/conf.d"
    - "/etc/authselect"


- name: Press LDAP client configuration
  ansible.builtin.template:
    src: client_ldap.conf.j2
    mode: "0644"
    dest: "{{ openldap_server_app_path }}/ldap.conf"

- name: Press SSSD configuration
  ansible.builtin.template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: "0600"
  notify:
    - restart_login_services

- name: Enable oddjobd
  ansible.builtin.systemd:
    name: oddjobd
    state: started
    enabled: true

- name: Ensure SSSD is enabled and running
  ansible.builtin.systemd:
    name: sssd
    state: started
    enabled: true

- name: Press authselect user-nsswitch.conf
  template:
    src: user_nsswitch.conf.j2
    dest: "{{ authselect_user_nsswitch_conf_file }}"
    mode: 0644
    owner: root
    group: root
  notify:
    - update_pam_with_authselect
    - restart_login_services
    - restart_autofs

- name: Get current authselect config
  command: authselect current -r
  register: authselect_current_raw
  check_mode: no
  changed_when: false
  failed_when:
    - authselect_current_raw.rc != 0
    - '"No existing configuration detected" not in authselect_current_raw.stdout'

- name: Set fact authselect_force true if no existing configuration detected.
  set_fact:
    authselect_force: true
  when:
    - '"No existing configuration detected" in authselect_current_raw.stdout'

- name: Verify current authselect profile and features are in the desired state
  set_fact:
    authselect_current_profile: "{{ authselect_current_raw.stdout.split()[0] }}"
    authselect_current_features: "{{ authselect_current_raw.stdout.split()[1:] }}"
  changed_when:
    - authselect_profile != authselect_current_profile or
      authselect_features | sort != authselect_current_features | sort or
      authselect_current_raw.failed
  notify:
    - update_pam_with_authselect






