---
- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Add /etc/hosts entry for ldap server
  lineinfile:
    dest: /etc/hosts
    state: present
    line: "{{ openldap_server_ip }} {{ openldap_server_domain_name }}"

- name: Install the openldap and required Packages for RedHat
  yum:
    name: "{{ openldap_server_pkgs }}"
    state: present
  when: ansible_os_family == 'RedHat'


- name: Install the openldap and required Packages for Ubuntu
  apt:
    name: "{{ openldap_server_pkgs }}"
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'
