---

- name: Install the openldap and required Packages for RedHat
  yum:
    name: "{{ openldap_server_pkgs }}"
    state: present
  when: ansible_os_family == 'RedHat'


- name: Install the openldap and required Packages for Ubuntu
  apt:
    name: "{{ openldap_server_pkgs }}"
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'
