---

- name: Install the openldap and required Packages for RedHat
  yum:
    name: "{{ openldap_server_pkgs }}"
    state: present
  when: ansible_os_family == 'RedHat'


- name: Install the openldap and required Packages for Ubuntu
  apt:
    name: "{{ openldap_server_pkgs }}"
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install ansible python dependencies for ldap configuration
  pip:
    name: "{{ item.name }}"
    version: |
      {% if (item.version is defined) and (item.version|length > 0) %}
        {{ item.version }}
      {% else %}
        (omit)
      {% endif %}
    state: |
      {% if (item.state is defined) and (item.state|length > 0) %}"
        {{ item.state }}
      {% else %}
        present
      {% endif %}
  loop: "{{ openldap_python_pkgs }}"
  notify:
    - restart_login_services
  when:
    - openldap_python_pkgs is defined
    - openldap_python_pkgs|length > 0
