---
- name: Users OU
  ldap_entry:
    bind_dn: "{{ openldap_server_bind_dn }}"
    bind_pw: "{{ openldap_server_rootpw }}"
    dn: "{{ users_ou }}"
    objectClass: organizationalUnit
    state: present
  notify:
    - restart nslcd
    - restart nscd

- name: Groups OU
  ldap_entry:
    bind_dn: "{{ openldap_server_bind_dn }}"
    bind_pw: "{{ openldap_server_rootpw }}"
    dn: "{{ groups_ou }}"
    objectClass: organizationalUnit
    state: present
  notify:
    - restart nslcd
    - restart nscd

- name: Create Groups
  ldap_entry:
    bind_dn: "{{ openldap_server_bind_dn }}"
    bind_pw: "{{ openldap_server_rootpw }}"
    dn: "cn={{ item.key }},{{ groups_ou }}"
    objectClass:
      - posixGroup
      - top
    attributes:
      description: "{{ item.value.description }}"
      gidNumber: "{{ item.value.gid }}"
    state: present
  notify:
    - restart nslcd
    - restart nscd
  with_dict: "{{ ssh_groups }}"

- name: Set Group Membership
  ldap_attr:
    bind_dn: "{{ openldap_server_bind_dn }}"
    bind_pw: "{{ openldap_server_rootpw }}"
    dn: "cn={{ item.key }},{{ groups_ou }}"
    name: memberUid
    values: "{{ item.value.members }}"
    state: exact
  notify:
    - restart nslcd
    - restart nscd
  with_dict: "{{ ssh_groups }}"

- name: "Set up SSH users"
  ldap_entry:
    bind_dn: "{{ openldap_server_bind_dn }}"
    bind_pw: "{{ openldap_server_rootpw }}"
    dn: "uid={{ item.key }},{{ users_ou }}"
    objectClass:
      - top
      - posixAccount
      - person
      - inetOrgPerson
      - shadowAccount
      - ldapPublicKey
    attributes:
      gidNumber: "{{ item.value.gid }}"
      uidNumber: "{{ item.value.uid }}"
      homeDirectory: "/home/{{ item.key }}"
      loginShell: "{{ item.value.shell | default('/bin/bash') }}"
      givenName: "{{ item.value.givenname }}"
      sn: "{{ item.value.sn }}"
      mail: "{{ item.value.mail }}"
      gecos: "{{ item.value.gecos }}"
      userPassword: "{{ item.value.password }}"
      cn: "{{ item.value.cn }}"
      sshPublicKey: "{{ item.value.pubkey }}"
    state: "{{ item.value.state }}"
  loop: "{{ ssh_users|dict2items }}"
  register: ssh_users_added
  notify:
    - restart nslcd
    - restart nscd

- meta: flush_handlers
