---
- name: Include os specific vars
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags:
    - always

- name: Add /etc/hosts entry for ldap server
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    state: present
    line: "{{ openldap_server_ip }} {{ openldap_server_domain_name }} {{ openldap_server_domain_name.split('.')[0] }}"
  tags:
    - openldap-hosts

- name: Wait for locks
  ansible.builtin.include_tasks:
    file: wait_for_locks.yml

- name: Configure client LDAP and SSSD
  ansible.builtin.include_tasks:
    file: openldap_client.yml
    apply:
      tags:
        - openldap-client
  tags:
    - openldap-client

- name: Configure SSH server LDAP settings
  ansible.builtin.include_tasks:
    file: openldap_sshd.yml
    apply:
      tags:
        - openldap-sshd
  when:
    - ansible_system != 'OpenBSD'
  tags:
    - openldap-sshd

- name: Include AutoFS installation tasks
  ansible.builtin.include_tasks:
    file: openldap_autofs.yml
    apply:
      tags:
        - openldap-automount
  when:
    - shared_storage | default(false) | bool
  tags:
    - openldap-automount
