---
- name: Remove NSCD and NSLCD
  block:
    - name: Stop NSLCD
      ansible.builtin.systemd:
        name: nslcd
        state: stopped
        enabled: false

    - name: Stop NSCD (Debian)
      ansible.builtin.systemd:
        name: nscd
        state: stopped
        enabled: false
      when:
        - ansible_os_family == "Debian"

    - name: Uninstall NSCD and NSLCD packages
      ansible.builtin.package:
        name:
          - nscd
          - nslcd
        state: absent

- name: SSSD Setup Tasks
  block:
    - name: Install SSSD + LDAP client packages
      ansible.builtin.package:
        name: "{{ openldap_client_pkgs }}"
        state: present
        update_cache: true

    - name: Ensure SSSD is enabled and running
      ansible.builtin.service:
        name: sssd
        state: started
        enabled: true

    - name: Enable oddjobd
      ansible.builtin.systemd:
        name: oddjobd
        state: started
        enabled: true

    - name: Remove previously created sssd snippets if present
      ansible.builtin.file:
        path: /etc/sssd/conf.d/
        state: absent

    - name: Ensure paths for openldap, sssd and authselect configs exist
      ansible.builtin.file:
        state: directory
        dest: "{{ item }}"
        mode: "0644"
      loop:
        - "{{ openldap_server_app_path }}"
        - "/etc/sssd/conf.d"
        - "/etc/authselect"

    - name: Install LDAP client configuration
      ansible.builtin.template:
        src: client_ldap.conf.j2
        mode: "0644"
        dest: "{{ openldap_server_app_path }}/ldap.conf"

    # - name: Press SSSD configuration
    #   ansible.builtin.template:
    #     src: sssd.conf.j2
    #     dest: /etc/sssd/sssd.conf
    #     owner: root
    #     group: root
    #     mode: "0600"
    #     validate: sssctl config-check
    #   notify:
    #     - restart_login_services

- name: Generate and validate SSSD configuration
  block:
    - name: Install SSSD configuration
      ansible.builtin.template:
        src: sssd.conf.j2
        dest: /etc/sssd/sssd.conf
        owner: root
        group: root
        mode: "0600"
        backup: true
      register: sssd_config_updated
      notify:
        - restart_login_services
        - invalidate_sss_cache
        - restart_autofs
    - name: Validate SSSD configuration
      ansible.builtin.command:
        cmd: >-
          sssctl config-check
      changed_when: false
      when:
        - sssd_config_updated is changed

  rescue:
    - name: Restore original SSSD configuration
      ansible.builtin.copy:
        remote_src: true
        src: "{{ sssd_config_updated['backup_file'] }}"
        dest: /etc/sssd/sssd.conf
      when:
        - sssd_config_updated.backup_file is defined
        - sssd_config_updated is changed
      notify:
        - restart_login_services
        - invalidate_sss_cache
        - restart_autofs
  always:
    - name: Remove SSSD config backup
      ansible.builtin.file:
        path: "{{ sssd_config_updated['backup_file'] }}"
        state: absent
      when:
        - sssd_config_updated.backup_file is defined
        - sssd_config_updated is changed




- name: PAM configuration via Authselect
  block:
    - name: Press authselect user-nsswitch.conf
      template:
        src: user_nsswitch.conf.j2
        dest: "{{ authselect_user_nsswitch_conf_file }}"
        mode: 0644
        owner: root
        group: root
      notify:
        - update_pam_with_authselect
        - restart_login_services
        - invalidate_sss_cache
        - restart_autofs

    - name: Get current authselect config
      command: authselect current -r
      register: authselect_current_raw
      check_mode: no
      changed_when: false
      failed_when:
        - authselect_current_raw.rc != 0
        - '"No existing configuration detected" not in authselect_current_raw.stdout'

    - name: Set fact authselect_force true if no existing configuration detected.
      set_fact:
        authselect_force: true
      when:
        - '"No existing configuration detected" in authselect_current_raw.stdout'

    - name: Verify current authselect profile and features are in the desired state
      set_fact:
        authselect_current_profile: "{{ authselect_current_raw.stdout.split()[0] }}"
        authselect_current_features: "{{ authselect_current_raw.stdout.split()[1:] }}"
      changed_when:
        - authselect_profile != authselect_current_profile or
          authselect_features | sort != authselect_current_features | sort or
          authselect_current_raw.failed
      notify:
        - update_pam_with_authselect
        - invalidate_sss_cache





