---
- name: Install autofs packages
  ansible.builtin.package:
    name: "{{ openldap_autofs_pkgs }}"
    state: present
    update_cache: true

- name: Start AutoFS service
  ansible.builtin.systemd:
    name: autofs
    state: started
    enabled: true

- name: Start rpcbind service (RHEL)
  ansible.builtin.systemd:
    name: rpcbind
    state: started
    enabled: true

- name: Remove previously created autofs file if present
  ansible.builtin.copy:
    dest: |
      {% set autofs_pathh = "" %}
      {% if ansible_os_family == "RedHat" %}
      {% set autofs_path = "/etc/sysconfig/autofs" %}
      {% elif ansible_os_family == "Debian" %}
      {% set autofs_path = "/etc/default/autofs" %}
      {% endif %}
      {{ autofs_path }}
    content: |
      #
      # Init system options
      #
      # If the kernel supports using the autofs miscellanous device
      # and you wish to use it you must set this configuration option
      # to "yes" otherwise it will not be used.
      #
      USE_MISC_DEVICE="yes"
      #
      # Use OPTIONS to add automount(8) command line options that
      # will be used when the daemon is started.
      #
      #OPTIONS=""
  notify:
    - restart_autofs

- name: Include the directory master map
  ansible.builtin.lineinfile:
    path: /etc/auto.master
    regexp: "^\\s*#?\\s*\\+auto\\.master\\s*$"
    line: "+auto.master"
  notify:
    - restart_autofs

- name: Flush Handlers
  ansible.builtin.meta: flush_handlers
