---
- name: wait_for_locks | Wait or cloud-init to finish
  community.general.cloud_init_data_facts:
    filter: status
  register: ciresult
  until:
    - ciresult.cloud_init_data_facts.status.v1.stage is defined
    - not ciresult.cloud_init_data_facts.status.v1.stage
  retries: 50
  delay: 10

- name: wait_for_locks | Wait for automatic system updates
  ansible.builtin.shell:
    cmd: fuser {{ item }} >/dev/null 2>&1
  loop:
    - /var/lib/dpkg/lock
    - /var/lib/dpkg/lock-frontend
    - /var/lib/rpm/.rpm.lock
  register: lockresult
  until:
    - lockresult.rc == 1
  changed_when:
    - lockresult.rc == 0
  failed_when: false
  retries: 50
  delay: 10
