---
- name: wait_for_locks | Test for cloud-init
  ansible.builtin.shell:
    cmd: command -v cloud-init
    executable: /bin/bash
  register: cicheck
  changed_when: cicheck is not failed
  ignore_errors: true

- name: wait_for_locks | Wait or cloud-init to finish
  community.general.cloud_init_data_facts:
    filter: status
  register: ciresult
  until:
    - ciresult.cloud_init_data_facts.status.v1.stage is defined
    - not ciresult.cloud_init_data_facts.status.v1.stage
  retries: 50
  delay: 10
  when:
    - cicheck is defined
    - cicheck is not failed

- name: wait_for_locks | Wait for automatic system updates
  ansible.builtin.shell:
    cmd: fuser {{ item }} >/dev/null 2>&1
  loop:
    - /var/lib/dpkg/lock
    - /var/lib/dpkg/lock-frontend
  register: lockresult
  until:
    - lockresult.rc == 1
  changed_when:
    - lockresult.rc == 0
  retries: 50
  delay: 10
  when:
    - ansible_os_family|lower == "debian"

- name: wait_for_locks | Wait for automatic system updates
  ansible.builtin.shell:
    cmd: fuser /var/lib/rpm/.rpm.lock >/dev/null 2>&1
  register: lockresult
  until:
    - lockresult.rc == 1
  changed_when:
    - lockresult.rc == 0
  retries: 50
  delay: 10
  when:
    - (ansible_os_family|lower) == "redhat"
