---
- name: Restart SSSD
  listen: restart_login_services
  ansible.builtin.systemd:
    name: sssd
    state: restarted
    enabled: true

- name: Restart SSHD
  listen: restart_login_services
  ansible.builtin.systemd:
    name: "{{ sshd_service }}"
    state: restarted
    enabled: true
    daemon_reload: true

- name: Restart SystemD LoginD
  listen: restart_login_services
  ansible.builtin.systemd:
    name: systemd-logind
    state: restarted
    enabled: true

- name: Restart AutoFS
  listen: restart_autofs
  ansible.builtin.systemd:
    name: autofs
    state: restarted
    enabled: true

- name: Update PAM with authselect
  listen: update_pam_with_authselect
  command: >-
    authselect select {{ authselect_profile }}
    {{ authselect_features | join(' ') }}
    {% if authselect_force %}--force{% endif %}

- name: Invalidate SSS Cache
  listen: invalidate_sss_cache
  command: >-
    sss_cache -E -A -R
